# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
#   - MediumFollowersCountPlugin:
#       username: zhgchgli
# Automatically fetch Github repo star count
#   - GithubRepoStarsCountPlugin:
#       - ZhgChgLi/ZMarkupParser
#       - ZhgChgLi/ZReviewTender
#       - ZhgChgLi/ZMediumToMarkdown
#       - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id: "G-M6J9SBDC1F"

# HTML Title
title: "SolSalt's Links"

# Avatar image path
avatar: "./images/solsalt-icon_white@300x.png"

# Name section text
name: "SOLSALT"

# Tagline section text
tagline: >-
  Relief You Can Feel. Rest You Deserve. Fuel Your Sol.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-rss"
      text: "Website"
      url: "https://www.thesolsalt.com/discount/welcome10"
      alt: "Sol Salt's Website"
      title: "SolSalt's Website"
      target: "_blank"
  - link:
      icon: "fa-solid fa-user-plus"
      text: "Email List"
      url: "https://www.sendfox.com/solsalt/"
      alt: "Sol Salt's Email List"
      title: "SolSalt's Email List"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/profile.php?id=61566759776296&mibextid=ZbWKwL"
      title: "Facebook"
      alt: "Sol Salt's Facebook"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/thesolsalt/"
      title: "Instagram"
      alt: "Sol Salt's Instagram"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:thesolsalt@gmail.com"
      title: "Email: thesolsalt@gmail.com"
      alt: "thesolsalt@gmail.com"
      target: "_blank"

# Footer text
footer: >
  Hi there! Follow us on Facebook or Instagram.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://www.thesolsalt.com" target="_blank">SolSalt</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
